### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by wongshington** [nwelchr/Test_Readme#2]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md)
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

**Comment by wongshington** [comment]
+ just need to number the MVPs and then add in how long you expect those to take

**Comment by forestwelch** [comment]
Fixed all pending issues!

Changes made:
- Ordered required MVPs chronologically and added time estimates on them (did not add dates... is that ok?).
- Moved 'Deploy to Heroku' MVP until later (I figure we won't need to do that until the end of the week or so).
