### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by wongshington** [nwelchr/Test_Readme#4]
- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by wongshington** [comment]
+ definitely, if a user is looking at their playlists/songs/albums, then feel free to use that current_user method under the hood, but allow for the ability to still ask for and receive information about other user's albums/playlists/songs etc.
+ we can talk about how to trim down those queries tomorrow too

**Comment by forestwelch** [comment]
Fixed all pending issues!

Changes made:
1. Formatted all API Endpoint wildcard variables in `snake_case`.
2. Removed unnecessary navigation to `playlists` through `/users/:user_id`, because of (1) the association between `playlists` and `users` and (2) the fact that `POST`/`PATCH`/`DELETE` requests can only be done by the current user.
