### ISSUE TITLE
Sample State Shape

### ISSUE THREAD

**Issue by wongshington** [nwelchr/Test_Readme#5]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema (Ex: if you create a `img_url` key in the state, make sure your database also has a column that contains an `img_url`)
- [x] Correctly formatted
    - [x] Sample state is rendered with 3 back ticks before and after. This will display the state as a code block instead of a giant line of text
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by wongshington** [comment]
+ your errors will likely only be separated into their concers: playlistErrors, SongErrors, sessionErrors, etc ->> won't need delete playlist to manage it's own error
+ you could do genre's a couple different ways, one involves making them their own table, another would mean using a constant in your model and assigning one before an entry is saved for a specific table(albums or songs)
+ wouldn't worry about tracking progress right now, that'll be influenced by how you end up playing the actual media files anyways
+ about is fine to be a  lot of text. as long as you aren't encountering any weird formatting because it's all in one db entry you should be fine

**Comment by forestwelch** [comment]
Not sure if I fixed all the issues, but I changed things around a bit (mostly cleaned things up and added examples to anywhere I had empty strings).
