### ISSUE TITLE
Wire Frames and Component Hierarchy

### ISSUE THREAD

**Issue by wongshington** [nwelchr/Test_Readme#6]
- [x] All routes listed in the routes wiki page is also listed in the component hierarchy
- [x] Each component, if necessary, has route, state, and other components it renders [example](https://github.com/appacademy/bluebird/wiki/component-hierarchy)
- [x] Necessary components are wrapped in a container
- [x] Correctly formatted
    - [x] Bullet point hierarchy
    - [x] Component names are displayed with `inline coding text` (backticks)
- [x] Wireframes included
- [x] Every component listed in the component hierarchy wiki page has at least one wireframe
- [x] Every MVPs listed on the MVP wiki page has at least one wireframe
- [x] Every route listed on the route wiki page has at least one wireframe
- [x] Contains Containers
- [x] Contains Lists
- [x] Contains ListItems
- [x] Correctly formatted
  - [x] Wireframe images display on the page
  - [x] Every wireframe has a header title

**Comment by wongshington** [comment]
+ will likely need a container for the side nav buttons
+ your wireframes are meant to be a loose idea of hwo the components will be rendered so there's likely to be overlap for sure
+ we'll discuss drying up some of this code tomorrow too

**Comment by forestwelch** [comment]
Attempted to clean this up!

Changes made:
1.) Added necessary routes from routes file
2.) Imported wireframes into document (they're still not very consistent though, I was unsure how to do the wireframes when I need to DRY up my hierarchy a lot)
